---
apiVersion: v1
kind: ConfigMap
metadata:
  name: curator-config
  namespace: kube-system
data:
  action_file.yml: |-
    ---
    actions:
      1:
        action: snapshot
        description: >-
          Snapshot logstash- prefixed indices older than 90 days (based on index
          creation_date) with the default snapshot name pattern of
          'curator-%Y%m%d%H%M%S'.  Wait for the snapshot to complete.  Do not skip
          the repository filesystem access check.  Use the other options to create
          the snapshot.
        options:
          repository: s3-backup
          name:
          ignore_unavailable: False
          include_global_state: True
          partial: False
          wait_for_completion: True
          skip_repo_fs_check: False
          timeout_override:
          continue_if_exception: False
          disable_action: False
        filters:
        - filtertype: pattern
          kind: prefix
          value: logstash-
          exclude:
        - filtertype: age
          source: creation_date
          direction: older
          unit: days
          unit_count: 90
          exclude:
      2:
        action: delete_indices
        description: "Clean up ES by deleting old indices"
        options:
          timeout_override:
          continue_if_exception: False
          disable_action: False
        filters:
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 90
          field:
          stats_result:
          epoch:
          exclude: False
  config.yml: |-
    ---
    # Remember, leave a key empty if there is no value.  None will be a string,
    # not a Python "NoneType"
    client:
      hosts:
        - elasticsearch-logging
      port: 9200
      url_prefix:
      use_ssl: False
      certificate:
      client_cert:
      client_key:
      ssl_no_validate: False
      http_auth:
      timeout: 30
      master_only: False

    logging:
      loglevel: INFO
      logfile:
      logformat: default
      blacklist: ['elasticsearch', 'urllib3']
