---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-s3-snapshot-repository-for-es
spec:
  template:
    metadata:
      name: create-s3-snapshot-repository-for-es
    spec:
      containers:
      - name: snapshot
        image: faraazkhan/es-curator-s3-setup
      restartPolicy: Never
---
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: curator
  namespace: kube-system
spec:
  schedule: 1 0 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curator
            image: bobrik/curator
            args: ["--config", "/etc/config/config.yml", "/etc/config/action_file.yml"]
            volumeMounts:
              - name: config-volume
                mountPath: /etc/config
          volumes:
            - name: config-volume
              configMap:
                name: curator-config
          restartPolicy: OnFailure
